.config/btop/themes/catppuccin_mocha.theme:
  type: "file"
  url: "https://raw.githubusercontent.com/catppuccin/btop/main/catppuccin_mocha.theme"
  refreshPeriod: 168h

.config/bat/themes/Catppuccin-mocha.tmTheme:
  type: "file"
  url: "https://raw.githubusercontent.com/catppuccin/bat/main/Catppuccin-mocha.tmTheme"
  refreshPeriod: 168h
